# -*- coding: utf-8 -*-
"""Copy of DBMS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_XGOMuzn92cpCxMJOCWljIWCqHV8Zaqd
"""

# ✅ Install dependencies (Colab or local)
!pip install --quiet diffusers transformers accelerate scipy safetensors

# ✅ Import required libraries
from diffusers import StableDiffusionPipeline
import torch
from PIL import Image
import matplotlib.pyplot as plt

# ✅ Load a public anime model (no login needed)
model_id = "gsdf/Counterfeit-V2.5"  # Anime style model

# ✅ Initialize the pipeline
pipe = StableDiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float32,
    safety_checker=None  # Disable safety if needed (some anime may trigger it)
)

# ✅ Move to GPU if available
device = "cuda" if torch.cuda.is_available() else "cpu"
pipe = pipe.to(device)

# ✅ Get user input
prompt = input("📝 Enter your anime concept: ")

# ✅ Generate image
print("🎨 Generating image...")
image = pipe(prompt).images[0]

# ✅ Save and show result
image_path = "anime_generated.png"
image.save(image_path)
plt.imshow(image)
plt.axis("off")
plt.title("✨ Generated Anime Image")
plt.show()